version: '3'

services:
  ubuntu1:
    build: .
    container_name: ubuntu1
    ports:
      - "2221:22"
    networks:
      - ansible_network

  ubuntu2:
    build: .
    container_name: ubuntu2
    ports:
      - "2222:22"
    networks:
      - ansible_network

  ubuntu3:
    build: .
    container_name: ubuntu3
    ports:
      - "2223:22"
    networks:
      - ansible_network

  ubuntu4:
    build: .
    container_name: ubuntu4
    ports:
      - "2224:22"
    networks:
      - ansible_network

  ubuntu5:
    build: .
    container_name: ubuntu5
    ports:
      - "2225:22"
    networks:
      - ansible_network

  ubuntu6:
    build: .
    container_name: ubuntu6
    ports:
      - "2226:22"
    networks:
      - ansible_network

networks:
  ansible_network:
    driver: bridge